"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Reclaim__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Reclaim__factory_1 = require("./Reclaim__factory");
Object.defineProperty(exports, "Reclaim__factory", { enumerable: true, get: function () { return Reclaim__factory_1.Reclaim__factory; } });
